{% set name = "python-debian" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://salsa.debian.org/python-debian-team/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.bz2
    sha256: a8d50b15ef5e2d88a7a8290474f7edbda9379b277918dd8e83bc139bc73afba5

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools >=61
    - setuptools_scm >=6.2
  run:
    - python
    - charset-normalizer

test:
  source_files:
    - conftest.py
    - tests
  imports:
    - debian
  requires:
    - pip
    - pytest
  commands:
    - pip check
    # subprocess.CalledProcessError: Command '['/usr/bin/ar', 'rU',
    # '/var/folders/h1/cwbpqsn95pb73q3m8nxpj47c0000gp/T/test_debfile.gcvtnwri/test.deb',
    # '/var/folders/h1/cwbpqsn95pb73q3m8nxpj47c0000gp/T/test_debfile.gcvtnwri/debian-binary',
    # '/var/folders/h1/cwbpqsn95pb73q3m8nxpj47c0000gp/T/test_debfile.gcvtnwri/control.tar.gz',
    # '/var/folders/h1/cwbpqsn95pb73q3m8nxpj47c0000gp/T/test_debfile.gcvtnwri/data.tar.gz']' returned non-zero exit status 1.
    - pytest -v --ignore=tests/test_debfile.py

about:
  home: https://salsa.debian.org/python-debian-team/python-debian
  license: GPL-2.0-or-later
  license_file: gpl-2.0.txt
  license_family: GPL
  summary: Debian package related modules
  description: |
    The debian Python modules work with Debian-related data formats,
    providing a means to read data from files involved in Debian packaging,
    and the distribution of Debian packages. The ability to create or edit
    the files is also available for some formats.
  doc_url: https://python-debian-team.pages.debian.net/python-debian
  dev_url: https://salsa.debian.org/python-debian-team/python-debian

extra:
  recipe-maintainers:
    - mbargull
